### ISSUE TITLE
allow_admin_changes=false blocks settings for tables

### ISSUE THREAD

**Issue by jellingsen** [craftcms/craft#38] opened 2019-02-06 16:24 UTC
When disabling allow_admin_changes in general.php and syncing settings with project.yaml the window for moving/adding/removing columns in tables are empty and the text "An unknown error occurred" appears at the top of the screen.

![selection_031](https://user-images.githubusercontent.com/14084128/52356115-fa25f100-2a33-11e9-9d8c-3c962cdae6d8.png)

Pressing the gear wheel results in an empty box:

![selection_032](https://user-images.githubusercontent.com/14084128/52356117-fa25f100-2a33-11e9-9adb-bec60120c73f.png)

**Comment by brandonkelly** [comment] 2019-02-06 17:51
Duplicate of craftcms/cms#3788

**Closed by brandonkelly** 2019-02-06 17:51 UTC
