### ISSUE TITLE
config.platform.php overrides system PHP version

### ISSUE THREAD

**Issue by sjelfull** [craftcms/craft#31] opened 2018-12-20 13:39 UTC
Composer's `config.platform.php` is set to 7.0 by default. This overrides the system's PHP Version, and prevents dependencies that requires newer versions of PHP from being installed.

Why is it set at all?

**Comment by brandonkelly** [comment] 2018-12-20 18:59
Duplicate of #7

**Closed by brandonkelly** 2018-12-20 18:59 UTC
